# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error Message')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=512, verbose_name='URL Pattern')),
                ('password', models.CharField(max_length=512, verbose_name='Password')),
                ('lockpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urllockdown.LockPage')),
            ],
        ),
    ]
